name: curve
channels:
  - defaults
  - conda-forge
  - nvidia
  - rapidsai
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - adwaita-icon-theme=48.0=h06a4308_0
  - aiodns=3.5.0=py310h06a4308_0
  - aiohappyeyeballs=2.6.1=py310h06a4308_0
  - aiohttp=3.12.15=py310hb25bd0a_0
  - aiosignal=1.4.0=py310h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - arrow-cpp=19.0.0=h16717c6_5
  - async-timeout=5.0.1=py310h06a4308_0
  - at-spi2-atk=2.34.2=hfac8509_1
  - at-spi2-core=2.36.0=h597f2ad_2
  - atk-1.0=2.36.0=ha1a6a79_0
  - attrs=24.3.0=py310h06a4308_0
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - blas=1.0=mkl
  - bokeh=3.8.0=pyhd8ed1ab_0
  - bottleneck=1.4.2=py310ha9d4c09_0
  - brotli-python=1.0.9=py310h6a678d5_9
  - brotlicffi=1.0.9.2=py310h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cachetools=6.2.0=pyhd8ed1ab_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.10.5=py310h06a4308_0
  - cffi=1.17.1=py310h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - clang-20=20.1.8=default_h4fcecc7_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cuda-bindings=12.9.1=py310hc395c1c_1
  - cuda-cccl=12.4.127=0
  - cuda-cccl_linux-64=12.4.127=ha770c72_2
  - cuda-crt-dev_linux-64=12.4.131=ha770c72_1
  - cuda-crt-tools=12.4.131=ha770c72_1
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart-dev=12.4.127=0
  - cuda-cudart-dev_linux-64=12.4.127=h85509e4_2
  - cuda-cudart-static_linux-64=12.4.127=h85509e4_2
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvcc-dev_linux-64=12.4.131=ha770c72_1
  - cuda-nvcc-impl=12.4.131=hd3aeb46_1
  - cuda-nvcc-tools=12.4.131=hd3aeb46_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-nvvm-dev_linux-64=12.4.131=ha770c72_1
  - cuda-nvvm-impl=12.4.131=h59595ed_1
  - cuda-nvvm-tools=12.4.131=h59595ed_1
  - cuda-opencl=12.4.127=h6a678d5_0
  - cuda-pathfinder=1.2.3=pyhcf101f3_0
  - cuda-profiler-api=12.4.127=0
  - cuda-python=12.9.1=pyhb6702c7_2
  - cuda-runtime=12.4.1=hb982923_0
  - cuda-version=12.4=hbda6634_3
  - cudf=25.08.00=cuda12_py310_250806_6cea3743
  - cuml=25.08.00=cuda12_py310_250806_b081fcd0
  - cupy=13.6.0=py310h8c3aed4_2
  - cupy-core=13.6.0=py310hbc0d89f_2
  - curl=8.15.0=h14366f7_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - cytoolz=1.0.1=py310ha75aee5_0
  - dask=2025.7.0=pyhe01879c_0
  - dask-core=2025.7.0=pyhe01879c_1
  - dask-cuda=25.08.00=py313_250806_bde9a4d3
  - dask-cudf=25.08.00=cuda12_py310_250806_6cea3743
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - dill=0.3.8=py310h06a4308_0
  - distributed=2025.7.0=pyhe01879c_0
  - distributed-ucxx=0.45.01=py_250806_c25d2cdb_h7e233d3
  - dlpack=0.8=h59595ed_3
  - epoxy=1.5.4=h7f8727e_2
  - expat=2.7.1=h6a678d5_0
  - fastrlock=0.8.3=py310h25320af_2
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.17.0=py310h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h55d465d_3
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.59.2=py310hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.5.0=py310h5eee18b_0
  - fsspec=2024.12.0=py310h06a4308_0
  - gdk-pixbuf=2.42.10=h64b468e_2
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - git=2.51.0=pl5382h000ed5b_0
  - git-lfs=3.7.0=h59e48b9_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - gobject-introspection=1.84.0=py310hcb37abf_0
  - graphite2=1.3.14=h295c915_1
  - gtk3=3.24.21=h40e4fd3_8
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=10.2.0=hdfddeaa_1
  - hf-xet=1.1.8=py310h84c0859_0
  - hicolor-icon-theme=0.17=h06a4308_2
  - icu=73.1=h6a678d5_0
  - idna=3.7=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.5.2=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.8=py310h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libboost=1.88.0=h9d9b81f_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libclang-cpp20.1=20.1.8=default_h4fcecc7_0
  - libclang13=20.1.8=default_hee3e7a4_0
  - libcublas=12.4.5.8=h99ab3db_1
  - libcublas-dev=12.4.5.8=0
  - libcudf=25.08.00=cuda12_250806_6cea3743
  - libcufft=11.2.1.3=h99ab3db_1
  - libcufile=1.9.1.3=h99ab3db_1
  - libcufile-dev=1.9.1.3=0
  - libcuml=25.08.00=cuda12_250806_b081fcd0
  - libcumlprims=25.08.00=cuda12_py310_250806_59064b25
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.15.0=hc1efc7f_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusolver-dev=11.6.1.9=0
  - libcusparse=12.3.1.170=h99ab3db_1
  - libcusparse-dev=12.3.1.170=0
  - libcuvs=25.08.00=cuda12_250806_9ce11a0f
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.1.0=h69a702a_5
  - libgd=2.3.3=h536bbd8_4
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.1.0=h767d61c_5
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libkrb5=1.21.3=h520c7b4_4
  - libkvikio=25.08.00=cuda12_9_250806_2f72c39a
  - libllvm15=15.0.7=he89c38a_4
  - libllvm20=20.1.8=h465586c_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.2.5.30=h99ab3db_1
  - libnuma=2.0.18=hb9d3cd8_3
  - libnvcomp=4.2.0.11=hb7e823c_1
  - libnvcomp-dev=4.2.0.11=hb7e823c_1
  - libnvfatbin=12.4.127=h7934f7d_2
  - libnvjitlink=12.4.127=h99ab3db_1
  - libnvjpeg=12.3.1.117=h6a678d5_1
  - libopengl=1.7.0=h5eee18b_2
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libraft=25.08.00=cuda12_250806_2fb92393
  - libraft-headers=25.08.00=cuda12_250806_2fb92393
  - libraft-headers-only=25.08.00=cuda12_250806_2fb92393
  - libre2-11=2024.07.02=h6a678d5_0
  - librmm=25.08.00=cuda12_250806_63a4d366
  - librsvg=2.56.3=hb0330b6_2
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtasn1=4.20.0=ha30cf84_0
  - libthrift=0.15.0=h5e7f578_3
  - libtiff=4.7.0=hde9077f_0
  - libtool=2.4.7=h6a678d5_0
  - libucxx=0.45.01=cuda12_250806_c25d2cdb
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.44.0=py310h0070a79_2
  - lmdb=0.9.31=hb25bd0a_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py310hb259640_1
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib=3.10.6=py310h06a4308_0
  - matplotlib-base=3.10.6=py310h71dd3da_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mesalib=25.1.5=h31e3550_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - msgpack-python=1.1.1=py310h03d9f68_1
  - multidict=6.1.0=py310h5eee18b_0
  - multiprocess=0.70.15=py310h06a4308_0
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - narwhals=2.5.0=pyhcf101f3_0
  - nccl=2.28.3=h115b396_1
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numba=0.61.2=py310h3477d8a_2
  - numba-cuda=0.14.1=py_0
  - numexpr=2.11.0=py310hf4471f9_0
  - nvidia-ml-py=12.575.51=pyhd8ed1ab_0
  - nvtx=0.2.13=py310h7c4b9e2_1
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.5.3=h26f9b46_1
  - orc=2.1.1=hd396ef6_0
  - packaging=25.0=py310h06a4308_0
  - pandas=2.3.2=py310h277b779_0
  - pango=1.50.7=h668f713_2
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.42=hebb0a14_1
  - perl=5.40.2=0_h5eee18b_perl5
  - pillow=11.3.0=py310hb1c3d2d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - poppler=24.09.0=h696634e_4
  - poppler-data=0.4.12=h06a4308_0
  - propcache=0.3.1=py310h5eee18b_0
  - protobuf=5.29.3=py310he621ea3_0
  - psutil=7.1.0=py310h7c4b9e2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycares=4.10.0=py310ha137689_0
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pylibcudf=25.08.00=cuda12_py310_250806_6cea3743
  - pylibraft=25.08.00=cuda12_py310_250806_2fb92393
  - pynvjitlink=0.7.0=12.9_py310_250625_3693c9cd_hd6618c4
  - pynvml=12.0.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=py310h06a4308_0
  - pyqt=6.9.1=py310hc79087c_0
  - pyqt6-sip=13.10.2=py310hee96239_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.18=h1a3bd86_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py310h5eee18b_0
  - python_abi=3.10=2_cp310
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - qtbase=6.9.2=h46e0f57_0
  - qtdeclarative=6.9.2=h55666de_0
  - qtsvg=6.9.2=h75a08ff_0
  - qttools=6.9.2=hc856bc8_0
  - qtwayland=6.9.2=h9f1b7ec_0
  - qtwebchannel=6.9.2=hbdd6827_0
  - qtwebsockets=6.9.2=hbdd6827_0
  - raft-dask=25.08.00=cuda12_py310_250806_2fb92393
  - rapids-dask-dependency=25.08.00=250806_fb4cb9f6
  - rapids-logger=0.1.1=h98325ef_0
  - rdma-core=58.0=h7934f7d_0
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - regex=2025.9.1=py310hee96239_0
  - requests=2.32.5=py310h06a4308_0
  - rich=14.1.0=pyhe01879c_0
  - rmm=25.08.00=cuda12_py310_250806_63a4d366
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.5.3=py310h922eef2_0
  - scikit-learn=1.7.2=py310h505adc9_0
  - scipy=1.15.3=py310h525edd1_0
  - setuptools=78.1.1=py310h06a4308_0
  - sip=6.12.0=py310h7934f7d_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchaudio=2.5.1=py310_cu124
  - tornado=6.5.1=py310h5eee18b_0
  - tqdm=4.67.1=py310h2f386ee_0
  - treelite=4.4.1=py310hebdfe98_1
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - ucx=1.18.1=h990bcc0_2
  - ucx-py=0.45.00=py310_250806_d53bdda0
  - ucxx=0.45.01=cuda12_py310_250806_c25d2cdb
  - unicodedata2=15.1.0=py310h5eee18b_1
  - urllib3=2.5.0=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.21.0=py310h5eee18b_0
  - wayland=1.24.0=hdac8c69_0
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxinerama=1.1.5=h50385e7_1
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.18.0=py310h5eee18b_0
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - accelerate==1.11.0
      - alembic==1.16.5
      - annotated-types==0.7.0
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - authlib==1.6.5
      - azure-core==1.35.1
      - azure-identity==1.25.1
      - azure-storage-blob==12.26.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - black==25.9.0
      - bleach==6.2.0
      - blessed==1.22.0
      - blinker==1.9.0
      - boto3==1.40.59
      - botocore==1.40.59
      - cfgutils==1.15.1
      - clang==20.1.5
      - colorama==0.4.6
      - comm==0.2.3
      - cpgqls-client==0.0.9
      - cramjam==2.11.0
      - cryptography==45.0.7
      - cyclopts==3.24.0
      - cython==3.1.4
      - databricks-sdk==0.67.0
      - datasets==4.3.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dnspython==2.8.0
      - docker==7.1.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - docutils==0.22.2
      - dpu-utils==0.6.1
      - email-validator==2.3.0
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fastapi==0.118.0
      - fastjsonschema==2.21.2
      - fastmcp==2.12.4
      - fastparquet==2024.11.0
      - flask==3.1.2
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.41.1
      - gpustat==1.1.1
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - graphviz==0.21
      - greenlet==3.2.4
      - gunicorn==23.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.2
      - huggingface-hub==0.35.3
      - inquirerpy==0.3.4
      - ipykernel==6.30.1
      - ipython==8.37.0
      - isodate==0.7.2
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jmespath==1.0.1
      - json5==0.12.1
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-path==0.3.4
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - lark==1.3.0
      - lazy-object-proxy==1.12.0
      - libclang==18.1.1
      - lightning-utilities==0.15.2
      - mako==1.3.10
      - matplotlib-inline==0.1.7
      - mcp==1.16.0
      - mistune==3.1.4
      - mlflow==3.4.0
      - mlflow-skinny==3.4.0
      - mlflow-tracing==3.4.0
      - more-itertools==10.8.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - openapi-core==0.19.5
      - openapi-pydantic==0.5.1
      - openapi-schema-validator==0.6.3
      - openapi-spec-validator==0.7.2
      - opentelemetry-api==1.37.0
      - opentelemetry-proto==1.37.0
      - opentelemetry-sdk==1.37.0
      - opentelemetry-semantic-conventions==0.58b0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parse==1.6.5
      - parso==0.8.5
      - pathable==0.4.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pfzy==0.3.4
      - platformdirs==4.4.0
      - prettytable==3.16.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pygraphviz==1.14
      - pyjoern==4.0.150.4
      - pyjwt==2.10.1
      - pynndescent==0.5.13
      - pyparser==1.0
      - pyperclip==1.11.0
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytokens==0.2.0
      - pytorch-metric-learning==2.9.0
      - pyzmq==27.1.0
      - referencing==0.36.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich-rst==1.3.1
      - rpds-py==0.27.1
      - rsa==4.9.1
      - s3transfer==0.14.0
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - setsimilaritysearch==1.0.1
      - smart-open==7.4.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.43
      - sqlparse==0.5.3
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.48.0
      - swifter==1.4.0
      - sympy==1.14.0
      - terminado==0.18.1
      - timeout-decorator==0.5.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - torch-geometric==2.6.1
      - torchmetrics==1.8.2
      - torchvision==0.24.0
      - traitlets==5.14.3
      - transformers==4.57.1
      - tree-sitter==0.25.2
      - tree-sitter-c-sharp==0.23.1
      - tree-sitter-embedded-template==0.25.0
      - tree-sitter-language-pack==0.10.0
      - tree-sitter-yaml==0.7.2
      - triton==3.5.1
      - types-python-dateutil==2.9.0.20250822
      - typing-inspection==0.4.2
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - uvicorn==0.37.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - werkzeug==3.1.1
      - wrapt==2.0.0
